sudo: false
language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
script:
  - python2.4 -m compileall -fq -x 'cloud/|/accelerate.py' .
  - python2.4 -m compileall -fq cloud/amazon/_ec2_ami_search.py cloud/amazon/ec2_facts.py
  - python -m compileall -fq .
